templates:
  torrent:
    transmission:
      host: localhost
      port: 9091
      ratio: 4
  tv:
    template: torrent
    thetvdb_lookup: yes
    exists_series:
      - /mnt/storage/Series/{{ tvdb_series_name }}
    series:
      - serie 1
      - serie 2
      - serie 3
    set:
      path: /mnt/storage/Series/{{ tvdb_series_name }}
      main_file_only: yes
      content_filename: "{{ tvdb_series_name }} - {{ tvdb_season }}x{{ tvdb_episode|pad(2) }} - {{ tvdb_ep_name|default('Missing title') }}"

tasks:
  Series-Primary:
    rss: http://mysite.com/myfeed.rss
    template: tv
